from .base import AssertFieldOutputTests
from .ar import ARLocalFlavorTests
from .at import ATLocalFlavorTests
from .au import AULocalFlavorTests
from .be import BELocalFlavorTests
from .br import BRLocalFlavorTests
from .ca import CALocalFlavorTests
from .ch import CHLocalFlavorTests
from .cl import CLLocalFlavorTests
from .cz import CZLocalFlavorTests
from .cn import CNLocalFlavorTests
from .de import DELocalFlavorTests
from .es import ESLocalFlavorTests
from .fi import FILocalFlavorTests
from .fr import FRLocalFlavorTests
from .gb import GBLocalFlavorTests
from .generic import GenericLocalFlavorTests
from .hr import HRLocalFlavorTests
from .id import IDLocalFlavorTests
from .ie import IELocalFlavorTests
from .il import ILLocalFlavorTests
from .in_ import INLocalFlavorTests
from .is_ import ISLocalFlavorTests
from .it import ITLocalFlavorTests
from .jp import JPLocalFlavorTests
from .kw import KWLocalFlavorTests
from .mk import MKLocalFlavorTests
from .nl import NLLocalFlavorTests
from .pl import PLLocalFlavorTests
from .pt import PTLocalFlavorTests
from .py import PYLocalFlavorTests
from .ro import ROLocalFlavorTests
from .ru import RULocalFlavorTests
from .se import SELocalFlavorTests
from .sk import SKLocalFlavorTests
from .tr import TRLocalFlavorTests
from .us import USLocalFlavorTests
from .uy import UYLocalFlavorTests
from .za import ZALocalFlavorTests
